- name: As the developer code writted in nodejs, we need to install the nodejs of version 20 by disabling the remaining versions
  ansible.builtin.command: dnf module disable nodejs

- name: enabling nodejs of version 20
  ansible.builtin.command: dnf module enable nodejs:20 -y


- name: installing the nodjes
  ansible.builtin.package:
    name: "{{ item }}"
    state: installed
  loop:
  - nodejs
  - mysql


- name: creating expense user
  ansible.builtin.user:
    name: expense

- name: importing from common role
  ansible.builtin.import_role:
    name: common
    tasks_from: app-pre-req


- name: installing build tool npm
  ansible.builtin.command: npm install
  args:
    chdir: /app

- name: placing the backend.service in required path
  ansible.builtin.template:
    src: backend.service.j2
    dest: /etc/systemd/system/backend.service


- name: donwloading pre required packages to connect to mysql_db
  ansible.builtin.pip:
    name:
    - PyMySQL
    - cryptography
    executable: pip3.9

- name: importing schema backend.sql the mysql_db
  community.mysql.mysql_db:
    login_user: "{{ login_user }}"
    login_host: "{{ login_host }}"
    login_password: "{{ login_password }}"
    target: /app/schema/backend.sql
    name: all
    state: import


- name: now restarting the backend service and reloading the daemon service
  ansible.builtin.systemd_service:
    daemon_reload: true
    state: restarted
    name: backend


