- name: removing the existing app/files
  ansible.builtin.file:
    path: "{{ app_location }}"
    state: absent
  ignore_errors: true

- name: creating the files/dir again
  ansible.builtin.file:
    path: "{{ app_location }}"
    state: directory
    
- name: donwloading the developer content
  ansible.builtin.unarchive:
    src: "https://expense-builds.s3.us-east-1.amazonaws.com/expense-{{ component }}-v2.zip"
    dest: "{{ app_location }}"
    remote_src: yes


  